### ISSUE TITLE
Requires libportmidi, but this is neither bundled, nor documented

### ISSUE THREAD

**Issue by sbergen** [icaroferre/MIDIRouter#2]
Got the following error when launchin manually
```
$ /Applications/MIDIrouter.app/Contents/MacOS/MIDIrouter
Traceback (most recent call last):
  File "/Users/icaroferre/Documents/PycharmProjects/midiRouter/midirouter.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mido/backends/portmidi.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/mido/backends/portmidi_init.py", line 20, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyiboot01_bootstrap.py", line 136, in __init__
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ctypes/__init__.py", line 347, in __init__
OSError: dlopen(libportmidi.dylib, 6): image not found
Failed to execute script midirouter
```

`brew install portmidi` helped, but it would be even better if this could be bundled in the app.

At the minimum, documenting this in the readme would be nice.

**Comment by icaroferre** [comment]
Sorry about the huge delay! I added portmidi as a requirement but I still need to investigate to see if it'd be possible to embed it into the app.
Any tips would be appreciated.
